pipeline {
    agent any

    environment {
        IMAGE_NAME = "nyobia-farrel-flask-app"
        DOCKER_ID  = "farrelsonfarrelovic"
    }

    stages {
        stage('Nettoyage') {
            steps {
                echo 'Nettoyage de l espace de travail...'
                deleteDir()
            }
        }

        stage('Clonage') {
            steps {
                git branch: 'main', 
                    url: 'https://github.com/FarrelsonFarrelovic/NYOBIA-FARREL-TP1-DOCKER.git'
            }
        }

        stage('Build Image') {
            steps {
                sh 'docker build -t ${IMAGE_NAME} .'
            }
        }

        stage('Push Docker Hub') {
            steps {
                // 'DOCKER_PASS' doit être créé dans Jenkins > Credentials
                withCredentials([string(credentialsId: 'DOCKER_PASS', variable: 'DOCKER_PASS')]) {
                    sh """
                        echo $DOCKER_PASS | docker login -u ${DOCKER_ID} --password-stdin
                        docker tag ${IMAGE_NAME} ${DOCKER_ID}/${IMAGE_NAME}:latest
                        docker push ${DOCKER_ID}/${IMAGE_NAME}:latest
                    """
                }
            }
        }
    }
}
